### ISSUE TITLE
Doesn't appear to be transferring

### ISSUE THREAD

**Issue by drew442** [erindru/openseedbox#15]
The torrent doesn't seem to transfer. If I look at the backend server the file is in the transmission download directory though.

![image](https://cloud.githubusercontent.com/assets/6799083/7360367/4f2d0202-ed8d-11e4-9cc6-d7ac33d64945.png)

I'm not sure where to look. Any ideas?

**Comment by XenZibe** [comment]
Software is bugged and does not show you this in real time. Edit the database for it to work.

**Comment by erindru** [comment]
There is a job called NodePollerJob that loops over each node and updates the database. If this is failing for some reason, then you wont see any progress.

Have a look at `logs/system.out` for error messages

**Comment by XenZibe** [comment]
@Override
	protected Object doGenericJob() {
		List<Node> nodes = Node.getActiveNodes();
		for (Node n : nodes) {	
// if (n.isReachable()) {
				List<ITorrent> torrents = n.getNodeBackend().listTorrents();
				List<Torrent> fromDb = Torrent.getByHash(getHashStrings(torrents));
				for (Torrent db : fromDb) {
					ITorrent match = findMatching(db, torrents);
					if (match != null) {
						db.merge(match);
					}
				}
				Torrent.batch().update(fromDb);
// }
		}	
		return null;
	}

Replace the section that looks like this with this.

WIll fix it ez pz

**Comment by drew442** [comment]
Thanks ZenZibe. That looks to have fixed it.
