### ISSUE TITLE
download button downloads empty file

### ISSUE THREAD

**Issue by drew442** [erindru/openseedbox#16]
I have a torrent downloaded and i can see it in the complete folder but when i choose download from the front end it downloads an empty file.

Where to from here?

**Comment by erindru** [comment]
You need to set a reverse proxy up in front the backend. There are example config files provided for nginx, in the openseedbox-server repo.

The reason for this is, file downloads are handled by sending an "X-Sendfile" (for Apache) or "X-Accel-Redirect" (for nginx) header that is picked up by the reverse proxy and triggers the download
