### ISSUE TITLE
How to set transmission configuration

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#20]
I want set some value in transmission config such as seed ratio, peer, speed lmit, etc

**Comment by erindru** [comment]
It uses the transmission `settings.json` file defined in `backend.base.path`

**Comment by psycholyzern** [comment]
Do I just need to change the value? Somehow the value did not applied.
If regular transmission setup, I need to stop the transmission-daemon and start editing the conffig. After starting transmission-daemon again, the config will be applied.

 But how to do that with openseedbox? "service transmission-daemon stop " give me unknown instance error.

**Comment by erindru** [comment]
Thats correct, just kill the openseedbox transmission-daemon via normal shell commands, eg `ps -A | grep trans` to get the PID and then `kill -9 [PID]`. Modify the config file, and then start it again from the Openseedbox admin

You might also be able to use `kill -HUP [PID]` to reload the config file without killing and starting transmission-daemon

**Comment by psycholyzern** [comment]
```kill -HUP [PID]``` save my times.. thanks :)
