### ISSUE TITLE
Is Nginx 1.2.6 a must?

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#21]
Im trying to add a new backend. Can I use Nginx 1.9.0? Or should I stick with 1.2.6?

**Comment by erindru** [comment]
Sure, give it a crack. 1.2.6 was the latest version at the time I wrote openseedbox, and I know that the modules (mod_zip and headers_more) work with it. But theres no reason why you cant try 1.9.0

**Comment by psycholyzern** [comment]
1.9.0 is a mainline version. i took desicion to use 1.8.0 because it is latest stable version. Works like a charm :)
