### ISSUE TITLE
Lowercase hash return "No such file or directory" error

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#23]
For some torrents, using lowercase hash does not work.

Example:
```
http://node2.example.com/download/95292748a6ed6621a0f572d186c1c793db27af8d?name=xxxxxx%5Bxxxxx%5D%2Fxxxxx.nfo
```
but using uppercase hash is working
```
http://node2.example.com/download/95292748A6ED6621A0F572D186C1C793DB27AF8D?name=xxxxxx%5Bxxxxx%5D%2Fxxxxx.nfo
```

in nginx error.log
![](http://i.imgur.com/sXsIDLD.png)

Is the any way so I can turn all hash into uppercase?

**Comment by erindru** [comment]
Ah yep, you added that torrent from a magnet link, right?

Unfortunately Openseedbox takes the "hash" part of the magnet link as gospel, which means that if it doesnt match exactly with the actual info_hash of the torrent once Transmission retrieves it, then the download links break.

To fix this particular issue, you would have to look at how torrents are added to openseedbox-backend, and convert the info_hash to lowercase before the "torrent-add" command is sent to transmission-daemon

**Comment by psycholyzern** [comment]
Meaning that, only torrent added by magnet link are affected by this issue?
Can you give me some hint where the files I should look into? java is pretty weird to me because Im used to PHP.

**Comment by erindru** [comment]
Yep that is correct.

Have a look at https://github.com/erindru/openseedbox-server/blob/master/app/com/openseedbox/backend/transmission/TransmissionBackend.java#L348 . If you convert the torrent hash to lowercase in the "torrent-add" request to Transmission, that should solve this particular issue.

**Comment by psycholyzern** [comment]
Do I need to restart Play! after modified the code?

**Comment by psycholyzern** [comment]
solved. thank you
