### ISSUE TITLE
Domain got indexed

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#24]
Im trying to stop bot from crawling my domain. Now, googlebot found my seedbox domain and appear on search engine.
I made robots.txt on ```/src/openseedbox/app/views/``` but when I access ```domain.com/robots.txt``` it cannot be found

**Comment by erindru** [comment]
You'll need to add a custom route, see this thread: https://groups.google.com/forum/#!topic/play-framework/WziCtkFnDEs

FYI OpenSeedbox is written using PlayFramework 1.x, the docs are here: https://www.playframework.com/documentation/1.2.7/home
