### ISSUE TITLE
Seeebox failing to add torrent

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#25]
Some magnet link cant be added, but torrent url can.
But somehow, many torrent cant be added even via magnet or torrent url.

This is log for frontend
http://slexy.org/view/s20DntAe6E

**Comment by erindru** [comment]
It looks like the backend is returning "null" when being asked to add a torrent. Can you please post the backend logs too?

**Comment by psycholyzern** [comment]
Backend 1: http://paste.ubuntu.com/11518719/
Backend 2: http://paste.ubuntu.com/11518794/

**Comment by psycholyzern** [comment]
I can confirm that some torrent cant be added on node1.. When I assign node2 to them, the torrent can be added again

**Comment by psycholyzern** [comment]
Ermmm.. No solution?

I got this on my new node

```INFO  ~ Error in RPC call: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: No response received after 60000```

**Comment by erindru** [comment]
It normally does that if transmission-daemon is not running or it cant talk to transmission-daemon

Make sure you arent running 2 transmission-daemons at the same time on the same node (the system starts one, and openseedbox starts one), this always leads to issues
