### ISSUE TITLE
settings.json got reset to default

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#28]
transmission config file on one of my node, got reset to default. I noticed my torrents got seeded over hundreds of GB and when I checked, the config files restored to default.
Is there any permanent way to change the config? rather than edit settings.json ?

**Comment by erindru** [comment]
settings.json *is* the permanent way to change the config. Make sure that transmission-daemon is NOT running before editing it, otherwise any changes you make will be overwritten when Transmission exits

**Comment by psycholyzern** [comment]
I edited the config and kill -HUP the transmission. It running great for a few weeks, then somehow yesterday it change the value to default
