### ISSUE TITLE
List of api command?

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#29]
I want to use api for managing the backend. Like adding, delete, status, of a torrent.. But I dont know what query need to be sent, can you list me all the api query available for backend?

**Comment by erindru** [comment]
There isnt a definitive list, just look at the routes file and the code in the controllers directory. https://github.com/erindru/openseedbox-server/blob/master/conf/routes and https://github.com/erindru/openseedbox-server/tree/master/app/controllers
