### ISSUE TITLE
Empty Downloads

### ISSUE THREAD

**Issue by sweatbar** [erindru/openseedbox#30]
Got everything working but download files are empty configured reverse proxy in nginx still the same any help will be appreciated?

**Comment by erindru** [comment]
What's your nginx config? You need to also set it up to expose your transmission 'complete' folder. Also have the files themselves actually downloaded correctly before you try and transfer them via nginx?

**Comment by sweatbar** [comment]
events {
  worker_connections  4096;  ## Default: 1024
}

 http {
    server_tokens off;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    server {
        listen 80;
        server_name seedbox.domain.net;

        gzip on;
        gzip_types "text/plain" "text/xml" "application/json";
        gzip_comp_level 9;

        merge_slashes off;
 proxy_method GET;

        location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto http;
                proxy_pass http://localhost:9001;
                more_clear_headers "Set-Cookie" "X-Archive-Files";
        }

        location /protected {
internal;
                alias /root/src/openseedbox/completed;
        }
}

}


This is my nginx configuration is there any mistakes in this one?

**Comment by sweatbar** [comment]
And how to make the complete folder of transmission expose? Please help.

**Comment by erindru** [comment]
Hmm, the folder should be `/root/src/openseedbox/complete`, not `/root/src/openseedbox/completed` (assuming that backend.base.path is set to `/root/src/openseedbox/` in application.conf)

When you download a torrent, do you see progress? And do the files get created in `/root/src/openseedbox/complete`?

**Comment by sweatbar** [comment]
Its downloading now thanks.
