### ISSUE TITLE
Error Your dedicated node is down. Please try again later.

### ISSUE THREAD

**Issue by sweatbar** [erindru/openseedbox#31]
When trying to add a torrent it gives this error "Error
Your dedicated node is down. Please try again later." but in the node status  it shows as "up"

any help?

**Comment by erindru** [comment]
Can you screenshot the node status page? Does it say "backend up" as well?

**Comment by sweatbar** [comment]
![node](https://cloud.githubusercontent.com/assets/9255451/10588883/0efadc00-76c6-11e5-8d18-27423de2eb8d.PNG)

btw this error comes only when  the user is in that node.

**Comment by erindru** [comment]
You might also have a firewall blocking the traffic. The "isReachable" check is done by InetAddress.isReachable() which seems to have some issues. see http://stackoverflow.com/questions/25301819/inetaddress-isreachable-only-works-when-firewall-is-turned-off

**Comment by erindru** [comment]
You could also comment out lines 121-126 of app/controllers/Client.java where the check occurs. https://github.com/erindru/openseedbox/blob/46c48284e65d6a12a2edb6bb24f2ec4021eac0b1/app/controllers/Client.java#L121

**Comment by sweatbar** [comment]
i dont have a firewall installed

**Comment by sweatbar** [comment]
that fixed it but the downloads are not downloading in full speed even though i put speed as -1. any fixes for that?

**Comment by erindru** [comment]
Do you mean not downloading at full speed from the BitTorrent network, or not downloading at full speed from the seedbox back to your PC?

**Comment by sweatbar** [comment]
not downloading at full speed from bit torrent client.

**Comment by sweatbar** [comment]
it seems to download at full speed but page is not getting it constantly i have to reload the page to get instant results

**Comment by erindru** [comment]
Openseedbox uses transmission-daemon for that, so you might want to check how transmission-daemon is configured and if you have blocked incoming connections etc. I cant help you further on the configuration of transmission-daemon unfortunately, if you get stuck you can try their forums: https://forum.transmissionbt.com/

**Comment by erindru** [comment]
> it seems to download at full speed but page is not getting it constantly i have to reload the page to get instant results

The torrent list will reload itself every 10 seconds, be patient
