### ISSUE TITLE
Can't resume downloads

### ISSUE THREAD

**Issue by sweatbar** [erindru/openseedbox#33]
When downloading from softwares like idm users cant resume the downloads, they have to re download it if cancelled any solutions to this?

**Comment by erindru** [comment]
You have to serve the files via the nginx reverse proxy in order for this to work. I don't know about IDM but I've been doing it fine for years via the Firefox DownThemAll extension

**Comment by sweatbar** [comment]
Configured nginx reverse proxy like this 

proxy_pass http://127.0.0.1:9001;

but still cant resume or pause downloads,

how to give download path as reverse proxy? there is no backend.website.com/download path in the server so do i have to give backend.website.com/src/openseedbox/complete folder as a reverse proxy folder?

**Comment by erindru** [comment]
The way it works is by sending an X-Archive-Files header that is picked up by nginx and used to serve the files. Did you look at the sample configs? Heres the one for opernseedbox-server: https://github.com/erindru/openseedbox-server/blob/master/conf/openseedbox-server.nginx.conf

Notice that it defines a `/protected` endpoint. You need to change the `alias` directive to link to your /complete folder.

The `/protected` endpoint is what matches up with the value of `backend.download.xsendfile.path` in the openseedbox-server config file.

The `/download' is a URL endpoint handled by the Play! server that gets passed a filename and generates an X-Archive-Files header for nginx to pick up and actually trigger the download
