### ISSUE TITLE
Use frontend as a node?

### ISSUE THREAD

**Issue by makkesk8** [erindru/openseedbox#34]
I don't have plans to use more than a single server for this and I wonder if this will be supported too?

I guess it kinda is but since the frontend "requires" nginx too it would be a mess to use two nginx setups on a single box.

**Comment by erindru** [comment]
Yep its completely possible, you just need to merge the nginx configs. Firstly, you'll need to configure the Play! instances to run on different ports (eg, 9000 and 9001) and then create two server blocks in the nginx config that are also on different ports (eg 80, 81) and have the frontend/backend reverse proxy config respectively.

Then, in the UI, add a node with a URL like http://DNS.name.of.server:81
