### ISSUE TITLE
Duplicate downloads

### ISSUE THREAD

**Issue by sweatbar** [erindru/openseedbox#36]
hey if a user add a download file that already in server it shows an error instead how to make the user download that file from the server because its already downloaded. 

is it something to do with  this file 
https://github.com/erindru/openseedbox/blob/master/app/com/openseedbox/models/UserTorrent.java

**Comment by erindru** [comment]
This is not implemented properly / at all. See https://github.com/erindru/openseedbox/issues/26 . I'd welcome a pull request if you would like to implement this

**Comment by xabolcs** [comment]
Frontend does support the multiple user same torrent use case. See e.g. [torrent related jobs](https://github.com/erindru/openseedbox/tree/9befa8ac5cfd081ada0ff325df70d39481d41e70/app/com/openseedbox/jobs/torrent)!

[Backend is unaware](https://github.com/erindru/openseedbox-server/blob/4d7a146408a38e93314ff0efa7eaced7f62b2138/app/com/openseedbox/backend/transmission/TransmissionBackend.java#L350-L355) of Transmission daemon's [`torrent-duplicate`](https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt) return arg, wich is available from Transmission 2.80.

PR is coming. :+1:
