### ISSUE TITLE
stats.html shows no space and node.status db column is NULL

### ISSUE THREAD

**Issue by gregorkistler** [erindru/openseedbox#37]
Hi,

I´m running a setup since you´ve provided a solution to use Google´s OAuth without any issues so far since March or April this year. 
Today I made a dist upgrade from my Ubuntu 15.04 installation to 15.10 and noticed afterwards that all of a sudden the 'Free Space' and 'Used Space' counter was telling me values like -9 and 0 at the nodes.html and somehow also the status column in the MySQL DB wasn´t updated anymore. The latter I think already a longer time, since it should contain the output of 'uptime' and the mentioned time there was not really near to when I did the upgrade.
After I´ve removed the only node I use so far and added it again the status column says only NULL now.
Anyway I figured out that the LVM device mapper showed up a with a different name after the upgrade. Fixed it in the application.conf from the backend and that issue was solved.
But still no change regarding the table column and the stats.html details which express how much space is used and available throughout all (active) nodes.

I simply set up another default installation (no firewall, no reverse proxy, all version requirements were met) with a brand new Ubuntu 16.04. instance and also a 14.04.3 instance and the result was always the same.
Everything works and shows proper information, only the stats.html says still 0 bytes for both 'Total space available across all nodes' and 'Total space used across all nodes' and also the MySQL DB still shows NULL at the node.status column.

Do you have any clue what could be the reason?

Thanks and keep up the good work.

**Comment by erindru** [comment]
Hmm, I wrote this a long time ago so I cant remember the exact details. Looking at the code, it seems to only include the "active" nodes. Are your nodes set to "active"?

Also with regards to the "status" column, im not sure if its actually used in all circumstances, the getNodeStatus() function queries the node directly from the `/status` url on each node. Have you tried querying this manually from your web browser and looking at the data returned?

**Comment by gregorkistler** [comment]
Yep, the node is active and not marked as down. When I try one of the context paths from the routes file like /check or /status i.e. <ip or hostname>:9001/status I only get 'Invalid API key'.
To simplify the setup the two application server talk directly with each other not via reverse proxy.

**Comment by erindru** [comment]
The reverse proxy is necessary in order for file downloads to work. The files are served via the webserver and not via Play!, which only has 2 request threads available.

Sorry I forgot about the api key, you need to add it as a parameter to the url, eg /status?api_key=foo
The value of the api_key can be found at `backend.base.api_key` in the config file of the node

**Comment by gregorkistler** [comment]
Yes that´s clear that I need to use a reverse proxy for the whole functionality. Only in this case to figure out why there is no status written to the database I use a very basic installation.
/status returns proper values .. but somehow twice

{"data":{"uptime":"07:33:23 up 11:47,  1 user,  load average: 0.00, 0.01, 0.05","free-space-bytes":12071796736,"used-space-bytes":3646341120,"total-space-bytes":15718137856,"is-backend-installed":true,"base-directory":"/media/openseedbox","is-base-directory-writable":true,"backend-name":"transmission","backend-version":"transmission-daemon 2.82 (14160)","is-backend-running":true,"uptime":"07:33:23 up 11:47,  1 user,  load average: 0.00, 0.01, 0.05","free-space-bytes":12071796736,"used-space-bytes":3646341120,"total-space-bytes":15718137856,"is-backend-installed":true,"base-directory":"/media/openseedbox","is-base-directory-writable":true,"backend-name":"transmission","backend-version":"transmission-daemon 2.82 (14160)","is-backend-running":true},"success":true}

**Comment by gregorkistler** [comment]
Finally found the issue. Even if the web service is in place and provides the node status via API the [code](https://raw.githubusercontent.com/erindru/openseedbox/master/app/com/openseedbox/models/Node.java) in Node.java still preferred the status column in the database:

```
81	public INodeStatus getNodeStatus(boolean fromDb) {
82		if (fromDb) {
83			return status;
84		}
```

I´ve simply commented out line 83 and now it works.

**Comment by gregorkistler** [comment]
Nice one 👍
As my quick fix worked but had severe side-effects e.g. while the backend node was down or misconfigured you got an exception calling the /admin/stats page.
