### ISSUE TITLE
geeting error on console

### ISSUE THREAD

**Issue by nniku121** [erindru/openseedbox#38]
Error: Backend base path '/media/openseedbox' isnt writable!

where this folder will be created iam not able to understsand plz help me to solve this issue

**Comment by erindru** [comment]
You need to set `backend.base.path` in the config file to a writable location. This is where the torrent files get downloaded to.

**Comment by nniku121** [comment]
![testing](https://cloud.githubusercontent.com/assets/16560076/12285659/6b1223c2-b9e2-11e5-9a7e-6a5de4b6b604.png)

now iam getting this error plz help me to slove this issue

**Comment by erindru** [comment]
can you please post the logs from your openseedbox-server instance. theyre in `logs/system.out`

**Comment by nniku121** [comment]
05:14:35,327 INFO  ~ Starting transmission-daemon via: transmission-daemon --config-dir /root/openseedbox --pid-file /root/openseedbox/daemon.pid 2>&1
05:14:35,333 INFO  ~ Oddities starting transmission: /bin/sh: transmission-daemon: command not found
05:14:45,842 ERROR ~

@6ombjmcpa
Internal Server Error (500) for request GET /backend/restart?ext=json&api_key=NIKHILniku1211

Execution exception (In /app/com/openseedbox/backend/transmission/TransmissionBackend.java around line 107)
RuntimeException occured : Process didnt die in 10 seconds, exiting to prevent infinite loop.

play.exceptions.JavaExecutionException: Process didnt die in 10 seconds, exiting to prevent infinite loop.
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
        at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: Process didnt die in 10 seconds, exiting to prevent infinite loop.
        at com.openseedbox.backend.transmission.TransmissionBackend.sleepWhile(TransmissionBackend.java:107)
        at com.openseedbox.backend.transmission.TransmissionBackend.start(TransmissionBackend.java:70)
        at com.openseedbox.backend.transmission.TransmissionBackend.restart(TransmissionBackend.java:89)
        at controllers.Backend.restart(Backend.java:34)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        ... 1 more

**Comment by erindru** [comment]
`05:14:35,333 INFO ~ Oddities starting transmission: /bin/sh: transmission-daemon: command not found`

Install `transmission-daemon`....

**Comment by nniku121** [comment]
download is not starting ??

![sdfgj](https://cloud.githubusercontent.com/assets/16560076/12286311/0d5d2522-b9e9-11e5-9910-73b7f6990216.png)

root@new:~# ps -A | grep transmission
 9698 ?        00:00:00 transmission-da
 9735 ?        00:00:00 transmission-da

do i need to stop one othe the transmission

**Comment by erindru** [comment]
Yes you do, you need to kill the one that was started by the system and then remove it from starting on startup. Openseedbox will start its own transmission-daemon instance, it needs to do this so that it can configure it correctly

**Comment by nniku121** [comment]
how to solve this problem when different users add the same torrent which another user have added then that user is getting error and that torrent is not getting added :( plz help thank u 
![problem](https://cloud.githubusercontent.com/assets/16560076/12297301/8b19402e-ba32-11e5-9a20-c7200cbed6e2.png)

**Comment by erindru** [comment]
This problem is currently unsolved, the workaround is to give each user a dedicated backend node

**Comment by erindru** [comment]
Also if you make each user an admin, they can switch to the other user that has the torrent via the user switcher in the top right
