### ISSUE TITLE
Nginx config for dedicated proxy container

### ISSUE THREAD

**Issue by gregorkistler** [erindru/openseedbox#43]
Within the last days I split up the involved services and only run one per container. Meanwhile I have one for MySQL, one for the frontend, one for the backend, one Nginx (serves both - frontend and backend) and one for gathering logs.
So far everythings works, except one thing: I can´t download completed files using the web GUI.
The Nginx config of course still points to a local folder which doesn´t exist in my new Nginx container.

What needs to be done in order to achieve my goal? Working with proxy_pass I guess but had no luck yet.

Quick´n´dirty solution would be to simply RO mount the complete folder locally in the Nginx container but would be nice to get it done the right way.

Any suggestions are much appreciated.

**Comment by redabourial** [comment]
can i have the details (folder path, and request uri) maybe a rewrite rule (https://www.nginx.com/blog/creating-nginx-rewrite-rules/) could fix this

**Comment by gregorkistler** [comment]
Paths and locations are basically untouched and the same as in the original files
https://github.com/erindru/openseedbox/blob/master/docker/nginx.conf
https://github.com/erindru/openseedbox-server/blob/master/docker/nginx.conf
https://github.com/erindru/openseedbox-server/blob/master/docker/application.conf

Here´s a gist of my own ones:
https://gist.github.com/gregorkistler/61566a8bbda27179fb378d9f5866d922

The folder where downloaded files are stored is /media/openseedbox/complete/

For example /media/openseedbox/complete/765ae306425db568953fc573688734bc7827d1c9/debian-8.6.0-s390x-netinst.iso

and the Nginx tries to serve the file like this:
https://openseedbox:8443/download/765ae306425db568953fc573688734bc7827d1c9?name=debian-8.6.0-s390x-netinst.iso

As long as the Play! application and Nginx are in the same container it works as designed.

**Comment by gregorkistler** [comment]
Will close the issue since my own approach works quite well.
