### ISSUE TITLE
Create a new account in 9000

### ISSUE THREAD

**Issue by wesleynunes121** [erindru/openseedbox#7]
when i try create a new account i get this information 

"400. That’s an error.
OpenID auth request contains an unregistered domain: http://myserver:9000/auth/authenticate"

when i try with myopenid 

"Error
Cannot verify your OpenID "

because of that, i cant enter on application

**Comment by erindru** [comment]
This is now fixed in the latest code, you need to set up an app in the Google Developer Console but you can now use Google OpenID Connect to sign in (see the README for how to set up the app in Google Developer Console)
