### ISSUE TITLE
java.lang.NullPointerException 

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#9]
I got this error in homepage for a user. Any way to remove or disable this message?

**Comment by wesleynunes121** [comment]
your backend is like that?
![135](https://cloud.githubusercontent.com/assets/9297984/6993800/fff45c4e-dad6-11e4-8a92-f4742e4520e6.png)

**Comment by erindru** [comment]
@psycholyzern without a stack trace I cannot tell you why that error occured. I think once you create a Plan and add the user to a Plan, it will go away

**Comment by xabolcs** [comment]
This should be fixed now! 👍
